-- Rollback: 20260530000002_create_accounting_chart_of_accounts_reconciliation_tables
DROP TRIGGER IF EXISTS accounting_chart_of_accounts_reconciliation_discrepancies_updated_at ON accounting_chart_of_accounts_reconciliation_discrepancies;
DROP FUNCTION IF EXISTS update_accounting_chart_of_accounts_reconciliation_discrepancies_updated_at();
DROP TRIGGER IF EXISTS accounting_chart_of_accounts_reconciliation_reports_updated_at ON accounting_chart_of_accounts_reconciliation_reports;
DROP FUNCTION IF EXISTS update_accounting_chart_of_accounts_reconciliation_reports_updated_at();
DROP TABLE IF EXISTS accounting_chart_of_accounts_reconciliation_discrepancies;
DROP TABLE IF EXISTS accounting_chart_of_accounts_reconciliation_reports;
DROP TYPE IF EXISTS accounting_review_status;
DROP TYPE IF EXISTS accounting_discrepancy_type;
DROP TYPE IF EXISTS accounting_reconciliation_status;
