#!/usr/bin/env bash
#
# Heroku deploy helper for proxypay (Issue #418).
#
# The in-dashboard "Deploy to Heroku" button is powered entirely by app.json.
# This script mirrors that flow from the command line for CI / scripting:
#   1. creates the app,
#   2. provisions Postgres + Redis addons,
#   3. writes the environment variables generated by setup-env.js,
#   4. pushes the repository to Heroku,
#   5. runs post-deployment verification against /ready.
#
# Prerequisites:
#   * Heroku CLI installed and authenticated (heroku login)
#
# Usage:
#   STELLAR_ISSUER_SECRET="S..." ./scripts/deploy/deploy-heroku.sh my-app-name
#
# Optional env:
#   STACK  Heroku stack. Use "container" (Dockerfile) or "heroku-22" (Node.js
#          buildpack). Default: container

set -euo pipefail

APP_NAME="${1:-}"
if [ -z "$APP_NAME" ]; then
  echo "usage: $0 <app-name>   e.g. $0 proxypay-staging" >&2
  exit 1
fi

STACK="${STACK:-container}"

echo "==> [1/6] Creating Heroku app: ${APP_NAME}"
heroku apps:create "${APP_NAME}" --stack "${STACK}"

echo "==> [2/6] Provisioning Postgres addon"
heroku addons:create heroku-postgresql:basic --app "${APP_NAME}" --wait

echo "==> [3/6] Provisioning Redis addon"
heroku addons:create heroku-redis:mini --app "${APP_NAME}" --wait

echo "==> [4/6] Generating environment variables"
node "$(dirname "$0")/setup-env.js" --print heroku > .deploy.env

echo "==> [5/6] Applying environment variables"
while IFS='=' read -r key value; do
  [ -z "$key" ] && continue
  [ -z "$value" ] && continue
  heroku config:set "${key}=${value}" --app "${APP_NAME}"
done < .deploy.env

heroku config:set --app "${APP_NAME}" \
  "NODE_ENV=production" \
  "STELLAR_NETWORK=${STELLAR_NETWORK:-testnet}"
rm -f .deploy.env

echo "==> [6/6] Pushing to Heroku"
heroku git:remote --app "${APP_NAME}"
git push heroku HEAD:main

echo "==> Post-deployment verification:"
echo "    ./scripts/deploy/verify-deployment.sh \"https://${APP_NAME}.herokuapp.com\""
