/**
 * Flaky Test Detector
 *
 * Runs the Jest test suite N times and records tests that produce inconsistent
 * results (pass on some runs, fail on others). Newly-detected flaky tests are
 * appended to quarantine.json and the dashboard is updated.
 *
 * Usage:
 *   npm run test:flaky
 *   npx tsx tests/flaky/detect-flaky.ts --runs=10 --pattern="<name>"
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface TestResult {
  fullName: string;
  status: 'passed' | 'failed' | 'pending';
  failureMessages: string[];
}

interface FlakyEntry {
  testName: string;
  fullName: string;
  passCount: number;
  failCount: number;
  flakyScore: number;
  firstSeen: string;
  lastFailureMessage: string;
  status: 'quarantined' | 'monitoring' | 'resolved';
}

interface QuarantineRegistry {
  version: string;
  description: string;
  quarantined: FlakyEntry[];
  resolved: FlakyEntry[];
}

interface FlakyReport {
  generatedAt: string;
  totalRuns: number;
  totalTests: number;
  flakyTests: FlakyEntry[];
  stableTests: number;
  summary: { newlyFlaky: number; alreadyQuarantined: number; resolved: number };
}

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const ROOT = path.resolve(__dirname, '../..');
const QUARANTINE_PATH = path.join(__dirname, 'quarantine.json');
const REPORT_PATH = path.join(__dirname, 'report.json');
const DASHBOARD_PATH = path.join(__dirname, 'dashboard.md');

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

function parseArgs(): { runs: number; pattern?: string } {
  const args = process.argv.slice(2);
  let runs = 5;
  let pattern: string | undefined;
  for (const a of args) {
    if (a.startsWith('--runs=')) runs = parseInt(a.split('=')[1], 10);
    if (a.startsWith('--pattern=')) pattern = a.split('=')[1];
  }
  return { runs, pattern };
}

// ---------------------------------------------------------------------------
// Single suite run
// ---------------------------------------------------------------------------

function runSuite(
  run: number,
  pattern?: string,
): { passed: number; failed: number; results: TestResult[] } {
  console.log(`\n[Run ${run}] Executing test suite...`);

  const cmd = [
    'npx jest',
    '--forceExit',
    '--testPathIgnorePatterns=tests/pact',
    '--no-coverage',
    '--maxWorkers=2',
    '--json',
    pattern ? `--testNamePattern="${pattern}"` : '',
  ]
    .filter(Boolean)
    .join(' ');

  let raw = '';
  try {
    raw = execSync(cmd, {
      cwd: ROOT,
      env: { ...process.env, NODE_ENV: 'test', CI: 'true', JEST_RETRIES: '0' },
      stdio: ['ignore', 'pipe', 'pipe'],
      timeout: 300_000,
    }).toString();
  } catch (err: unknown) {
    raw = (err as { stdout?: Buffer }).stdout?.toString() ?? '';
  }

  const start = raw.indexOf('{');
  if (start === -1) {
    console.warn(`[Run ${run}] No JSON output found`);
    return { passed: 0, failed: 0, results: [] };
  }

  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(raw.slice(start));
  } catch {
    console.warn(`[Run ${run}] JSON parse error`);
    return { passed: 0, failed: 0, results: [] };
  }

  const results: TestResult[] = [];
  for (const suite of (parsed.testResults as Array<{ testResults?: Array<{
    fullName: string; status: string; failureMessages: string[] }> }>) ?? []) {
    for (const t of suite.testResults ?? []) {
      results.push({
        fullName: t.fullName,
        status: t.status as TestResult['status'],
        failureMessages: t.failureMessages ?? [],
      });
    }
  }

  const passed = results.filter((r) => r.status === 'passed').length;
  const failed = results.filter((r) => r.status === 'failed').length;
  console.log(`[Run ${run}] ✅ ${passed} passed  ❌ ${failed} failed`);
  return { passed, failed, results };
}

// ---------------------------------------------------------------------------
// Dashboard update
// ---------------------------------------------------------------------------

function writeDashboard(report: FlakyReport, quarantined: FlakyEntry[]): void {
  const now = new Date().toISOString();
  const rows = quarantined
    .map(
      (t) =>
        `| ${t.testName.slice(0, 55).padEnd(55)} | ${t.flakyScore} | ${t.passCount} | ${t.failCount} | ${t.firstSeen.slice(0, 10)} | ${t.status} |`,
    )
    .join('\n');

  const content = `# Flaky Test Dashboard

> Auto-generated by \`tests/flaky/detect-flaky.ts\` — Last updated: ${now}

## Summary

| Metric | Value |
|--------|-------|
| Total runs last scan | ${report.totalRuns} |
| Total tests observed | ${report.totalTests} |
| Flaky tests detected | ${report.flakyTests.length} |
| Currently quarantined | ${quarantined.length} |
| Stable tests | ${report.stableTests} |

## Quarantined Tests

${
  quarantined.length === 0
    ? '> No tests currently quarantined.'
    : `| Test Name | Score | Passes | Fails | First Seen | Status |
|-----------|-------|--------|-------|------------|--------|
${rows}`
}

## How to Resolve a Quarantined Test

1. Find the entry in \`quarantine.json\`
2. Fix the root cause (timing, async state, shared fixtures)
3. Run \`npm run test:flaky:runs -- --pattern="<name>"\` (10 runs)
4. If 0 failures: move to \`resolved\` in \`quarantine.json\`, remove \`.skip\`

## Flaky Score Reference

\`flakyScore = failCount / (passCount + failCount)\`

| Score | Meaning |
|-------|---------|
| 0.0–0.1 | Occasionally flaky |
| 0.1–0.4 | Moderately flaky |
| 0.4–1.0 | Highly unreliable |
`;

  fs.writeFileSync(DASHBOARD_PATH, content);
  console.log(`📊 Dashboard → ${DASHBOARD_PATH}`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const { runs, pattern } = parseArgs();

  console.log('=================================================');
  console.log('  ProxyPay Flaky Test Detector');
  console.log(`  Runs: ${runs}${pattern ? `  Filter: "${pattern}"` : ''}`);
  console.log('=================================================');

  const registry: QuarantineRegistry = fs.existsSync(QUARANTINE_PATH)
    ? JSON.parse(fs.readFileSync(QUARANTINE_PATH, 'utf8'))
    : { version: '1.0.0', description: '', quarantined: [], resolved: [] };

  // Run suite N times
  const allResults: TestResult[][] = [];
  for (let i = 1; i <= runs; i++) {
    const { results } = runSuite(i, pattern);
    allResults.push(results);
  }

  // Aggregate pass/fail per test
  const map = new Map<string, { pass: number; fail: number; lastMsg: string }>();
  for (const runResults of allResults) {
    for (const t of runResults) {
      const e = map.get(t.fullName) ?? { pass: 0, fail: 0, lastMsg: '' };
      if (t.status === 'passed') e.pass++;
      if (t.status === 'failed') {
        e.fail++;
        e.lastMsg = t.failureMessages[0]?.slice(0, 500) ?? '';
      }
      map.set(t.fullName, e);
    }
  }

  // Find flaky (passed at least once AND failed at least once)
  const flakyTests: FlakyEntry[] = [];
  for (const [fullName, counts] of map.entries()) {
    if (counts.pass > 0 && counts.fail > 0) {
      const existing = registry.quarantined.find((q) => q.fullName === fullName);
      flakyTests.push({
        testName: fullName.split(' > ').pop() ?? fullName,
        fullName,
        passCount: counts.pass,
        failCount: counts.fail,
        flakyScore: parseFloat(
          (counts.fail / (counts.pass + counts.fail)).toFixed(2),
        ),
        firstSeen: existing?.firstSeen ?? new Date().toISOString(),
        lastFailureMessage: counts.lastMsg,
        status: existing ? 'quarantined' : 'monitoring',
      });
    }
  }

  flakyTests.sort((a, b) => b.flakyScore - a.flakyScore);

  // Merge new entries into registry
  const newlyFlaky = flakyTests.filter((f) => f.status === 'monitoring');
  for (const f of newlyFlaky) {
    registry.quarantined.push({ ...f, status: 'quarantined' });
  }
  fs.writeFileSync(QUARANTINE_PATH, JSON.stringify(registry, null, 2));

  // Write report
  const report: FlakyReport = {
    generatedAt: new Date().toISOString(),
    totalRuns: runs,
    totalTests: map.size,
    flakyTests,
    stableTests: map.size - flakyTests.length,
    summary: {
      newlyFlaky: newlyFlaky.length,
      alreadyQuarantined: flakyTests.filter((f) => f.status === 'quarantined').length,
      resolved: registry.resolved.length,
    },
  };
  fs.writeFileSync(REPORT_PATH, JSON.stringify(report, null, 2));
  console.log(`\n📋 Report → ${REPORT_PATH}`);

  writeDashboard(report, registry.quarantined);

  // Summary
  console.log('\n=================================================');
  console.log('  SUMMARY');
  console.log('=================================================');
  console.log(`  Total tests  : ${map.size}`);
  console.log(`  Flaky        : ${flakyTests.length}`);
  console.log(`  Newly added  : ${newlyFlaky.length}`);
  console.log(`  Stable       : ${report.stableTests}`);

  if (flakyTests.length > 0) {
    console.log('\n  ⚠️  Flaky tests:');
    for (const t of flakyTests) {
      console.log(`    [${t.flakyScore}] ${t.fullName}  (${t.passCount}✅ / ${t.failCount}❌)`);
    }
  } else {
    console.log('\n  ✅ No flaky tests detected!');
  }

  process.exit(newlyFlaky.length > 0 ? 1 : 0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
